title = "A Portfolio & Blog (by James)"

[author]
  name = "James Dixon"
  headline = "Fullstack Web Developer - Linux/FOSS Enthusiast - PC Gamer - Tech Wrangler - Cool Guy 😎"
  bio = "Fullstack Web Developer and Tech Wrangler"
  image = "img/gh_profile.jpg"
  links = [
    { email = "mailto:notjamesdixon@gmail.com" },
    { github = "https://github.com/lemonase" },
    { linkedin = "https://linkedin.com/in/james-dixon-147431109/" },
  ]
