# List of color schemes:
# https://nunocoracao.github.io/blowfish/docs/getting-started/#colour-schemes
colorscheme = "blowfish"
# colorScheme = "congo"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = true


[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  # defaultBackgroundImage = "/images/backgrounds/beach.jpg"
  # layout = "background"
  layout = "hero"
  homepageImage = "/images/backgrounds/beach.jpg"
  showRecent = false
  showMoreLink = true

[article]
  showDate = true
  showReadingTime = false
  showWordCount = false
  showSummary = false
  showPagination = true

[list]
  showPagination = false
