# List of color schemes:
# https://nunocoracao.github.io/blowfish/docs/getting-started/#colour-schemes
# colorScheme = "blowfish"
# colorScheme = "autumn"
# colorScheme = "forest"
# colorScheme = "avocado"
# colorScheme = "congo"
# colorScheme = "noir"
# colorScheme = "slate"
# colorScheme = "fire"

defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true


[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  # layout = "background"
  layout = "hero"
  homepageImage = "/images/backgrounds/beach.jpg"
  showRecent = false
  showMoreLink = true

[article]
  showDate = true
  showReadingTime = false
  showWordCount = false
  showSummary = false
  showPagination = true

[list]
  showPagination = false
  showHero = true
  heroStyle = "background"
